spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_boot_project_demo
    username: root
    password: admin
  application:
    name: WebApp

server:
  port: 10012

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10010/eureka/ # URL of the Eureka Server

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: hmy.webapp.entity, hmy.webapp.dto


